### ISSUE TITLE
Docker secret injection

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/duriel#31]
## Use case

We need the KONG ssl certificate private key to be injected via build process into docker secrets.
this is 
* secret name=kong-ssl-key
* secret value = base64(private key) (the base64 makes sure we can keep the line brakes and yet storeit on circle in an ENV var)

## Proposed solution

Allow section oc-secret-injection in task_template

In update build, check existing service secrets against task template and drop any secrets except {$servicename-consul-key} U {all secrets from task-template}

In create/update build, inject all secrets from task-template that are not already defined.

Note: this allows dropping secrets and creating new ones. However, changing the value of a secret is not supported.

**Comment by StefanTurbine** [comment]
### Notes: 
- list of current secrets: ['Spec'][''TaskTemplate]['ContainerSpec']['Secrets']
- entries in task_template.json: 
``` javascript 
{
"oc-secret-injection": {
      "monitoring-secret": "${circle_env_var_42}"
    }
}
```

### ToDo's:
#### Reading
- [ ] load secret-list from inspect
- [ ] load secret-list from task_template

#### Updating / Creating
- [ ] remove secret from service via ` service update --secret-rm ` 
- [ ] remove Secret vie EnvProxy 
- [ ] add Secret via EnvProxy 
- [ ] add secret to service via ` service update --secret-add `

### Questions:
1. What if a secret is used by multiple services and one wants to delete it? (Docker will not allow this)
2. An Update would be possible by reading the secret from running containers (as done with the consul-secrets). This would prevent manual magic :) It a full-replacement in every case the better solution?

**Comment by StefanTurbine** [comment]
example:
``` javascript
const example = {
	alpha: "i am a string",
	beta: {value: "i am not encoded"},
	gamma: {encoding: "base64", value: "aSBhbSBlbmNvZGVk"}
};
const expected = {
	alpha: "i am a string",
	beta: "i am not encoded",
	gamma: "i am encoded"
};
```

**Comment by StefanTurbine** [comment]
## TaskTemplate
```javascript
{
"oc-secret-injection": {
        "alpha": "i am a string",
	"beta": {"value": "i am not encoded"},
	"gamma": {"encoding": "base64", "value": "aSBhbSBlbmNvZGVk"}
    }
}
```
## Actions:
- Before docker-command execution --> Creation of new secrets
- Through docker-command (update/creation) --> adding/removing docker-secrets to service
- After Deployment --> cleanup (Deleting of docker secrets if possible)

**Comment by StefanTurbine** [comment]
done

**Comment by gr4per** [comment]
I guess in order to complete we would need to use this in kong.
